// Mocks generated by Mockito 5.3.2 from annotations
// in e_commerce_app/test/features/productCatalog/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:e_commerce_app/core/network/network_info.dart' as _i6;
import 'package:e_commerce_app/features/productCatalog/data/datasources/product_local_data_source.dart'
    as _i5;
import 'package:e_commerce_app/features/productCatalog/data/datasources/product_remote_data_source.dart'
    as _i2;
import 'package:e_commerce_app/features/productCatalog/data/models/product_item_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i2.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductItemModel>> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ProductItemModel>>.value(
            <_i4.ProductItemModel>[]),
      ) as _i3.Future<List<_i4.ProductItemModel>>);
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i5.ProductLocalDataSource {
  MockProductLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductItemModel>> getLastProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastProducts,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ProductItemModel>>.value(
            <_i4.ProductItemModel>[]),
      ) as _i3.Future<List<_i4.ProductItemModel>>);
  @override
  _i3.Future<void> cacheProducts(List<_i4.ProductItemModel>? productToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProducts,
          [productToCache],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
